Repository cloudquery-policies/azure, pull requests merged in 2022-02, with the labels that each got.

#20 feat: Add controls_against_malicious_code
  hipaa_hitrust_v9.2/policy.hcl
  queries/compute/asc_missingsystemupdates_audit.sql
  queries/compute/virtualmachines_antimalwareautoupdate_auditifnotexists.sql
  queries/compute/vmantimalwareextension_deploy.sql
Labels: feat

#19 feat: Add administrator_and_operator_logs
  hipaa_hitrust_v9.2/policy.hcl
  queries/monitor/activitylog_administrativeoperations_audit.sql
Labels: feat

#22 fix: Make Azure policies run successfully
  cis_v1.3.0/policy.hcl
  test/policy_cq_config.hcl
Labels: fix

#24 chore: Synced file(s) with cloudquery/.github
  .github/workflows/lint.yml
Labels: ignore-for-release
